// Generated by jevvium from the "forms-switch" criterion on ios (jev-1.13.0).
// It is a normal test: review it and edit it like any other code.
import { $, expect } from '@wdio/globals'

describe('forms-switch', () => {
  it('On the Forms screen, the user turns the switch on.', async () => {
    await $('~Forms').click()
    await $('~switch').click()
    await expect($('-ios predicate string:label == "Click to turn the switch OFF"')).toBeDisplayed()
  })
})
