// Generated by jevvium from the "login-invalid-email" criterion on ios (jev-1.13.0).
// It is a normal test: review it and edit it like any other code.
import { $, expect } from '@wdio/globals'

describe('login-invalid-email', () => {
  it('A user who tries to log in with a malformed email address is not logged in and is asked for a valid email address.', async () => {
    await $('~Login').click()
    await $('~input-email').setValue('not-an-email')
    await $('~input-password').setValue('Str0ngPassw0rd')
    await $('~button-LOGIN').click()
    await expect($('-ios predicate string:label == "Please enter a valid email address"')).toBeDisplayed()
  })
})
