// Generated by jevvium from the "login" criterion on ios (jev-1.13.0).
// It is a normal test: review it and edit it like any other code.
import { $, expect } from '@wdio/globals'

describe('login', () => {
  it('A registered user logs in with a valid email and password and is told they are logged in.', async () => {
    await $('~Login').click()
    await $('~input-email').setValue('qa.demo@example.com')
    await $('~input-password').setValue('Str0ngPassw0rd')
    await $('~button-LOGIN').click()
    await expect($('-ios predicate string:label == "You are logged in!"')).toBeDisplayed()
  })
})
