import type { Trace } from './explorer.ts'
import { expectationLocator, toSelector } from './locator.ts'
import type { Criterion } from './types.ts'

/**
 * Writes a passing run as a plain WebdriverIO + Mocha spec: fixed selectors,
 * fixed data, deterministic assertions. No model is involved when it runs.
 * Input values come from the criterion, because the trace never stores them.
 */
export function generateSpec(trace: Trace, criterion: Criterion): string {
  if (trace.outcome !== 'passed') {
    throw new Error(`Only passing runs can become tests; this run ${trace.outcome}: ${trace.reason}`)
  }

  const lines: string[] = []
  for (const step of trace.steps) {
    const taken = step.taken
    if (!taken) continue
    if (taken.type === 'type') {
      const value = criterion.inputs[taken.input!]
      if (value === undefined) throw new Error(`The criterion has no input named "${taken.input}"`)
      lines.push(`await $(${literal(taken.selector)}).setValue(${literal(value)})`)
    } else {
      lines.push(`await $(${literal(taken.selector)}).click()`)
    }
  }

  if (criterion.expect.length === 0) {
    lines.push('// TODO: this criterion has no expectations, so nothing proves the goal was reached.')
  }
  for (const expectation of criterion.expect) {
    const selector = toSelector(expectationLocator(expectation, trace.platform))
    lines.push(`await expect($(${literal(selector)})).toBeDisplayed()`)
  }

  const model = trace.steps.at(-1)?.decision.model ?? trace.provider
  return [
    `// Generated by jevvium from the "${criterion.id}" criterion on ${trace.platform} (${model}).`,
    '// It is a normal test: review it and edit it like any other code.',
    "import { $, expect } from '@wdio/globals'",
    '',
    `describe(${literal(criterion.id)}, () => {`,
    `  it(${literal(criterion.goal)}, async () => {`,
    ...lines.map((line) => `    ${line}`),
    '  })',
    '})',
    '',
  ].join('\n')
}

export function specFileName(trace: Trace): string {
  const safeId = trace.criterion.id.replace(/[^a-z0-9-]+/gi, '-')
  return `${safeId}.${trace.platform}.spec.ts`
}

/** A single-quoted TypeScript string literal. */
function literal(value: string): string {
  const escaped = value.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')
  return `'${escaped}'`
}
