import type { Trace } from './explorer.ts'
import { expectationLocator, toSelector } from './locator.ts'
import { redactor, restoreSelector } from './redact.ts'
import type { Criterion, Expectation } from './types.ts'

/**
 * Writes a passing run as a plain WebdriverIO + Mocha spec: fixed selectors,
 * fixed data, deterministic assertions. No model is involved when it runs.
 * Input values come from the criterion, because the trace never stores them.
 */
export function generateSpec(trace: Trace, criterion: Criterion): string {
  if (trace.outcome !== 'passed') {
    throw new Error(`Only passing runs can become tests; this run ${trace.outcome}: ${trace.reason}`)
  }
  checkPlatform(trace)
  assertSameCriterion(trace, criterion)

  const lines: string[] = []
  for (const taken of trace.steps.flatMap((step) => step.taken ?? [])) {
    const selector = restoreSelector(taken.selector, criterion.inputs)
    if (taken.type === 'type') {
      const value = criterion.inputs[taken.input!]
      if (value === undefined) throw new Error(`The criterion has no input named "${taken.input}"`)
      lines.push(`await $(${literal(selector)}).setValue(${literal(value)})`)
    } else {
      lines.push(`await $(${literal(selector)}).click()`)
    }
  }

  if (criterion.expect.length === 0) {
    lines.push('// TODO: this criterion has no expectations, so nothing proves the goal was reached.')
  }
  for (const expectation of criterion.expect) {
    const selector = toSelector(expectationLocator(expectation, trace.platform))
    lines.push(`await expect($(${literal(selector)})).toBeDisplayed()`)
  }

  const model = trace.steps.at(-1)?.decision.model ?? trace.provider
  const warning = trace.replay?.outcome === 'failed'
    ? [`// WARNING: when jevvium replayed these steps with plain Appium, they failed: ${oneLine(trace.replay.reason)}`]
    : []
  return [
    `// Generated by jevvium from the ${oneLine(JSON.stringify(criterion.id))} criterion on ${trace.platform} (${oneLine(model)}).`,
    '// It is a normal test: review it and edit it like any other code.',
    ...warning,
    "import { $, expect } from '@wdio/globals'",
    '',
    `describe(${literal(criterion.id)}, () => {`,
    `  it(${literal(criterion.goal)}, async () => {`,
    ...lines.map((line) => `    ${line}`),
    '  })',
    '})',
    '',
  ].join('\n')
}

export function specFileName(trace: Trace): string {
  checkPlatform(trace)
  return `${safeId(trace.criterion.id)}.${trace.platform}.spec.ts`
}

/** A criterion id made safe to use in a file name. */
export function safeId(id: string): string {
  return id.replace(/[^a-z0-9-]+/gi, '-').replace(/^-+|-+$/g, '') || 'criterion'
}

function checkPlatform(trace: Trace): void {
  if (trace.platform !== 'ios' && trace.platform !== 'android') {
    throw new Error(`The trace's platform must be ios or android, not ${JSON.stringify(trace.platform)}`)
  }
}

/**
 * The spec asserts what the criteria file says, so it must be the criterion that
 * was explored. The trace stores it with test data redacted, so compare it that way.
 */
function assertSameCriterion(trace: Trace, criterion: Criterion): void {
  const redact = redactor(criterion.inputs)
  const redacted = (e: Expectation) => ('id' in e ? { id: redact(e.id) } : { text: redact(e.text) })
  const explored = JSON.stringify(trace.criterion)
  const given = JSON.stringify({ id: criterion.id, goal: redact(criterion.goal), expect: criterion.expect.map(redacted) })
  if (explored !== given) {
    throw new Error(
      `The criteria file doesn't match the one this trace explored (${JSON.stringify(trace.criterion.id)}). ` +
        'Explore it again after changing its goal or expectations.',
    )
  }
}

/** Keeps a value on one comment line. JSON.stringify leaves U+2028 and U+2029 as they are, and both end a comment. */
function oneLine(value: string): string {
  return value.replace(/[\r\n\u2028\u2029]+/g, ' ')
}

/** A single-quoted TypeScript string literal. */
function literal(value: string): string {
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029')
  return `'${escaped}'`
}
