// Generated by jevvium from the "mydemo-checkout" criterion on ios (jev-1.13.0).
// It is a normal test: review it and edit it like any other code.
// WARNING: when jevvium replayed these steps with plain Appium, they failed: element ("-ios predicate string:type == "XCUIElementTypeTextField" AND placeholderValue == "Maxim Winter"") still not existing after 15000ms
import { $, expect } from '@wdio/globals'

describe('mydemo-checkout', () => {
  it('A shopper buys the Sauce Labs Backpack - Black. They add it to the cart from the Catalog, proceed to checkout from the Cart, log in by picking bob@example.com from the list of usernames, enter a shipping address, enter a card with the card holder\'s name, review the order and place it.', async () => {
    await $('(//XCUIElementTypeCell)[1]').click()
    await $('~AddToCart').click()
    await $('~Cart-tab-item').click()
    await $('~ProceedToCheckout').click()
    await $('-ios predicate string:type == "XCUIElementTypeButton" AND name == "bob@example.com"').click()
    await $('-ios predicate string:type == "XCUIElementTypeButton" AND name == "Login"').click()
    await $('-ios predicate string:type == "XCUIElementTypeTextField" AND placeholderValue == "Rebecca Winter"').setValue('Jane Tester')
    await $('-ios predicate string:type == "XCUIElementTypeTextField" AND placeholderValue == "Mandorley 112"').setValue('42 Example Street')
    await $('-ios predicate string:type == "XCUIElementTypeTextField" AND placeholderValue == "Truro"').setValue('Springfield')
    await $('-ios predicate string:type == "XCUIElementTypeTextField" AND placeholderValue == "89750"').setValue('12345')
    await $('-ios predicate string:type == "XCUIElementTypeTextField" AND placeholderValue == "United Kingdom"').setValue('United States')
    await $('-ios predicate string:type == "XCUIElementTypeButton" AND name == "To Payment"').click()
    await $('-ios predicate string:type == "XCUIElementTypeTextField" AND placeholderValue == "Maxim Winter"').setValue('Jane Tester')
    await $('-ios predicate string:type == "XCUIElementTypeTextField" AND placeholderValue == "3258 1265 7568 7896"').setValue('4111111111111111')
    await $('-ios predicate string:type == "XCUIElementTypeTextField" AND placeholderValue == "03/25"').setValue('1230')
    await $('-ios predicate string:type == "XCUIElementTypeTextField" AND placeholderValue == "123"').setValue('737')
    await $('-ios predicate string:type == "XCUIElementTypeButton" AND name == "Review Order"').click()
    await $('-ios predicate string:type == "XCUIElementTypeButton" AND name == "Place Order"').click()
    await expect($('-ios predicate string:label == "Checkout Complete"')).toBeDisplayed()
    await expect($('~ContinueShopping')).toBeDisplayed()
  })
})
