// Generated by jevvium from the "mydemo-cart-two-backpacks" criterion on ios (jev-1.13.0).
// It is a normal test: review it and edit it like any other code.
import { $, expect } from '@wdio/globals'

describe('mydemo-cart-two-backpacks', () => {
  it('From the Catalog, the shopper adds the Sauce Labs Backpack - Black and then the Sauce Labs Backpack - Green to the cart, going back to the Catalog with its tab in between, and opens the Cart.', async () => {
    await $('(//XCUIElementTypeCell)[1]').click()
    await $('~AddToCart').click()
    await $('~Catalog-tab-item').click()
    await $('(//XCUIElementTypeCell)[2]').click()
    await $('~AddToCart').click()
    await $('~Cart-tab-item').click()
    await expect($('-ios predicate string:label == "2 Items"')).toBeDisplayed()
    await expect($('-ios predicate string:label == "$59.98"')).toBeDisplayed()
  })
})
