// Generated by jevvium from the "mydemo-shipping-zip-required" criterion on ios (jev-1.13.0).
// It is a normal test: review it and edit it like any other code.
// WARNING: when jevvium replayed these steps with plain Appium, they failed: The text "Please provide your zip." is not on screen at the end.
import { $, expect } from '@wdio/globals'

describe('mydemo-shipping-zip-required', () => {
  it('At checkout (add the Sauce Labs Backpack - Black to the cart from the Catalog, proceed to checkout from the Cart, log in by picking bob@example.com), a shopper who enters a shipping address without a zip code and continues to payment is asked for the zip code.', async () => {
    await $('(//XCUIElementTypeCell)[1]').click()
    await $('~AddToCart').click()
    await $('~Cart-tab-item').click()
    await $('~ProceedToCheckout').click()
    await $('-ios predicate string:type == "XCUIElementTypeButton" AND name == "bob@example.com"').click()
    await $('-ios predicate string:type == "XCUIElementTypeButton" AND name == "Login"').click()
    await $('-ios predicate string:type == "XCUIElementTypeTextField" AND placeholderValue == "Rebecca Winter"').setValue('Jane Tester')
    await $('-ios predicate string:type == "XCUIElementTypeTextField" AND placeholderValue == "Mandorley 112"').setValue('42 Example Street')
    await $('-ios predicate string:type == "XCUIElementTypeTextField" AND placeholderValue == "Truro"').setValue('Springfield')
    await $('-ios predicate string:type == "XCUIElementTypeTextField" AND placeholderValue == "United Kingdom"').setValue('United States')
    await $('-ios predicate string:type == "XCUIElementTypeButton" AND name == "To Payment"').click()
    await expect($('-ios predicate string:label == "Please provide your zip."')).toBeDisplayed()
  })
})
