// Generated by jevvium from the "mydemo-add-to-cart" criterion on ios (jev-1.13.0).
// It is a normal test: review it and edit it like any other code.
import { $, expect } from '@wdio/globals'

describe('mydemo-add-to-cart', () => {
  it('From the Catalog, the shopper opens the Sauce Labs Backpack - Black, adds it to the cart and opens the Cart.', async () => {
    await $('(//XCUIElementTypeCell)[1]').click()
    await $('~AddToCart').click()
    await $('~Cart-tab-item').click()
    await expect($('-ios predicate string:label == "1 Items"')).toBeDisplayed()
    await expect($('~ProceedToCheckout')).toBeDisplayed()
  })
})
